# Generated by Django 3.1.4 on 2020-12-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0004_auto_20201230_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
